Repository sous-chefs/openssh, pull requests merged in 2023-08, with the labels that each got.

#170 Add Windows support
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  attributes/default.rb
  kitchen.exec.yml
  kitchen.yml
  libraries/helpers.rb
  metadata.rb
  mlc_config.json
  recipes/default.rb
  recipes/iptables.rb
  spec/spec_helper.rb
  spec/unit/recipes/default_windows_spec.rb
  test/integration/windows-default/default_spec.rb
Labels: Release: Minor

#173 No PAM option on Windows
  CHANGELOG.md
  attributes/default.rb
  spec/unit/recipes/default_windows_spec.rb
Labels: Bug, Release: Patch

#172 Automated PR: Standardising Files
  CHANGELOG.md
  kitchen.exec.yml
Labels: Release: Patch, Skip: Announcements

#175 Automated PR: Cookstyle Changes
  CHANGELOG.md
  attributes/default.rb
Labels: Release: Patch
